// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_running_info_json`, `get_instance_info`, `instance_event_receiver`, `instance_stop_notifier`, `ipv4_inet_to_host`, `parse_instance_id`, `push_core_event`, `push_session_message`, `push_snapshot`, `push_stopped`, `running_info_triggers_refresh`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MANAGER`, `RT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`

/// 初始化 FRB（应用启动时调用一次）。
Future<void> initApp() => RustLib.instance.api.crateApiEasytierInitApp();

Future<String> easytierVersion() =>
    RustLib.instance.api.crateApiEasytierEasytierVersion();

Future<void> parseConfig({required String toml}) =>
    RustLib.instance.api.crateApiEasytierParseConfig(toml: toml);

Future<String> runNetworkFromToml({required String toml}) =>
    RustLib.instance.api.crateApiEasytierRunNetworkFromToml(toml: toml);

Future<void> stopInstance({required String instanceId}) =>
    RustLib.instance.api.crateApiEasytierStopInstance(instanceId: instanceId);

Future<void> stopAllInstances() =>
    RustLib.instance.api.crateApiEasytierStopAllInstances();

Future<void> setTunFd({required String instanceId, required int fd}) => RustLib
    .instance
    .api
    .crateApiEasytierSetTunFd(instanceId: instanceId, fd: fd);

Future<String> getRunningInfoJson({required String instanceId}) => RustLib
    .instance
    .api
    .crateApiEasytierGetRunningInfoJson(instanceId: instanceId);

Future<bool> isInstanceRunning({required String instanceId}) => RustLib
    .instance
    .api
    .crateApiEasytierIsInstanceRunning(instanceId: instanceId);

/// 订阅实例会话：核心事件 + 快照 + stopped。
Stream<String> watchSession({required String instanceId}) =>
    RustLib.instance.api.crateApiEasytierWatchSession(instanceId: instanceId);
