name: easytier_frb
description: "将 EasyTier Rust 核心嵌入 Flutter 应用。"
version: 0.0.1
homepage:

environment:
  sdk: ^3.13.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: xyz.yhsj.easytier_frb
        pluginClass: EasytierFrbPlugin
        ffiPlugin: true
      ios:
        pluginClass: EasytierFrbPlugin
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

