[package]
name = "rust_lib_easytier_frb"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.13.0"
lazy_static = "1.5"
serde_json = "1.0"
toml = "0.8.12"
tokio = { version = "1.48", features = ["rt-multi-thread", "sync", "macros"] }
uuid = { version = "1.18", features = ["v4"] }
easytier = { git = "https://github.com/EasyTier/EasyTier.git", rev = "8428a89d2dabc94c97d370ec607c6ca142473626", default-features = false, features = [
    "wireguard",
    "websocket",
    "quic",
    "tun",
    "smoltcp",
    "socks5",
    "kcp",
    "faketcp",
    "magic-dns",
    "zstd",
] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
] }

[build-dependencies]
cargo_metadata = "0.23"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }



