// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `has_platform_tun_privileges`, `instance_manager`, `parse_core_instance_id`, `parse_instance_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MANAGER`, `RUNTIME`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `initialize_core`

/// 内嵌 EasyTier 核心报告的版本。
String easytierVersion() => RustLib.instance.api.crateApiCoreEasytierVersion();

/// 解析并校验 EasyTier TOML 配置，但不启动网络。
Future<void> validateToml({required String toml}) =>
    RustLib.instance.api.crateApiCoreValidateToml(toml: toml);

/// 返回配置是否需要创建 TUN 虚拟网卡。
bool configRequiresTun({required String toml}) =>
    RustLib.instance.api.crateApiCoreConfigRequiresTun(toml: toml);

/// 返回配置中声明的全部本地监听地址。
List<String> configListenerUrls({required String toml}) =>
    RustLib.instance.api.crateApiCoreConfigListenerUrls(toml: toml);

/// 返回配置中指定的静态虚拟 IPv4。
String? configVirtualIpv4({required String toml}) =>
    RustLib.instance.api.crateApiCoreConfigVirtualIpv4(toml: toml);

/// 返回当前进程是否具备创建系统 TUN 设备所需的权限。
bool hasTunPrivileges() => RustLib.instance.api.crateApiCoreHasTunPrivileges();

/// 启动一个 EasyTier 网络并返回核心实例 UUID。
Future<String> startFromToml({
  required String toml,
  required bool forceNoTun,
}) => RustLib.instance.api.crateApiCoreStartFromToml(
  toml: toml,
  forceNoTun: forceNoTun,
);

/// 将 Android VpnService 创建的 TUN 文件描述符交给 EasyTier。
Future<void> setTunFd({required String instanceId, required int fd}) =>
    RustLib.instance.api.crateApiCoreSetTunFd(instanceId: instanceId, fd: fd);

/// 停止一个 EasyTier 网络实例。
Future<void> stopInstance({required String instanceId}) =>
    RustLib.instance.api.crateApiCoreStopInstance(instanceId: instanceId);

/// 停止当前插件进程拥有的全部 EasyTier 网络实例。
Future<void> stopAllInstances() =>
    RustLib.instance.api.crateApiCoreStopAllInstances();

/// 返回指定实例当前是否已注册到核心管理器。
bool isInstanceRunning({required String instanceId}) =>
    RustLib.instance.api.crateApiCoreIsInstanceRunning(instanceId: instanceId);

/// 列出当前插件进程拥有的全部 EasyTier 实例 UUID。
List<String> listInstanceIds() =>
    RustLib.instance.api.crateApiCoreListInstanceIds();
