// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core_event_needs_snapshot`, `event_receiver`, `message`, `push`, `running_info_json`, `stop_notifier`

/// 返回一个 EasyTier 实例的原始 JSON 快照。
Future<String> getSessionSnapshot({required String instanceId}) => RustLib
    .instance
    .api
    .crateApiSessionGetSessionSnapshot(instanceId: instanceId);

/// 发送指定实例的 `snapshot`、`core_event` 和 `stopped` 消息。
Stream<CoreSessionMessage> watchSession({required String instanceId}) =>
    RustLib.instance.api.crateApiSessionWatchSession(instanceId: instanceId);

/// EasyTier 核心会话发出的内部消息。
class CoreSessionMessage {
  final String kind;
  final String json;

  const CoreSessionMessage({required this.kind, required this.json});

  @override
  int get hashCode => kind.hashCode ^ json.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreSessionMessage &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          json == other.json;
}
