// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Flutter 与 Rust 桥接协议的版本。
String bridgeVersion() => RustLib.instance.api.crateApiSimpleBridgeVersion();

/// 用于集成测试和运行诊断的最小往返调用。
String ping({required String payload}) =>
    RustLib.instance.api.crateApiSimplePing(payload: payload);
